project:
  type: website
  output-dir: docs

website:
  title: "Francesca Capuano"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Workshops
        menu:
          - text: LLMs vs. Human Language Processing
            href: workshops/llms-vs-human-language-processing/index.qmd
      - text: Stats Tutorials
        menu:
          - text: Acceptability Ratings
            href: tutorials/acceptability-ratings.qmd
          - text: Power Analysis
            href: tutorials/power-analysis.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true